### ISSUE TITLE
Create rent cap calculator

### ISSUE THREAD

**Issue by jpnelson** [Rent-Cap/website#10]
We'd like a URL (something like rentcap.info/calculator ) that lets you calculate what the maximum rent increase you can have is, based on your rent cap law coverage.

This would take your current rent (in dollars) and calculate what the maximum increase is (in dollars) taking into account the cap.

The formula is a little tricky, it's

```
maximum rent = previous rent * Max(1.05 + CPI, 1.10)
```

Where CPI = Regional CPI (eg. Bay Area) or if that doesn't exist, state level.

But on Jan 1 2020, if previously it was increased, it then drops back down

**Comment by reidjs** [comment]
https://docs.google.com/document/d/1IcFjxBmZRbTheXbnGTMHMFiG3NOe_ffL3XWnMZnB-4E/edit
