### ISSUE TITLE
Logo text looks tiny on mobile / generally

### ISSUE THREAD

**Issue by sh1mmer** [Rent-Cap/website#59]
The logo especially the text looks tiny on mobile. Ideally we can make it bigger or maybe separate the logo icon from the text and use a header for the text / logo combo so we can scale it responsively.

Example screen shot:

![Screenshot from 2019-12-15 16-49-47](https://user-images.githubusercontent.com/37673/70929232-7b043080-1fe7-11ea-9740-a4051bebff20.png)

**Comment by krpeacock** [comment]
Complete!
